### ISSUE TITLE
Need dataset

### ISSUE THREAD

**Issue by liuwb2001** [ShaohuiLiu/GNN_OPF_electricity_market#1]
Hi, I am so interested in this project and I want to do some prediction on electricity price. Could you please so kind to provide me with the dataset you used in your project? Myn email address is lwbaurora@gmail.com
Thanks a lot!

**Comment by ShaohuiLiu** [comment]
Thanks for your interests in our work. I just dropped you an email.

**Comment by yamizi** [comment]
Dear @ShaohuiLiu 
I am also interested in having access to your dataset. I am working on generative AI for power grids and your OPF dataset would be great to evaluate the approaches.
Let me know how to access it with my email: salah<DOT>ghamizi[AT]list.lu
Thank you

**Comment by ShaohuiLiu** [comment]
Hi @yamizi , I just dropped you an email but got rejected. Could you try the attached code to generate data directly? This should be more convenient.
`The response from the remote server was:
550 5.4.1 Recipient address rejected: Access denied. [[DB5PEPF00014B8E.eurprd02.prod.outlook.com](http://db5pepf00014b8e.eurprd02.prod.outlook.com/) 2023-11-20T15:01:59.259Z 08DBE74ED4DBBBE6]`
[data_gen.tar.gz](https://github.com/ShaohuiLiu/GNN_OPF_electricity_market/files/13416411/data_gen.tar.gz)

**Comment by ShaohuiLiu** [comment]
Sample datasets for 118-bus ac-OPF have been uploaded to [https://github.com/ShaohuiLiu/GNN_OPF_electricity_market/tree/main/data_gen/118_data](url)
